services:
  cqrs-es:
    build:
      context: ./cqrs-es
    environment:
        SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      postgres-cqrs-es:
        condition: service_healthy

  postgres-cqrs-es:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  cqrs-es-ui:
    build:
      context: ./cqrs-es-ui
    ports:
      - "8081:8080"
    depends_on:
      cqrs-es:
        condition: service_started